<a href="https://colab.research.google.com/github/vancucks/AtividadeCasa02/blob/main/teste_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd;

In [27]:
dados = {'nome':
         ['Argentina', 'Brasil', 'França', 'Italia', 'Reino unido'],
          'continente':
         ['America', 'America', 'Europa', 'Europa','Europa'],
         'extensao': [2780,8511,644,301,244],
         'corVerde': [0,1,0,1,0]
         }

In [29]:
siglas = ['AR','BR','FR','IT','UK']

In [30]:
paises = pd.DataFrame(dados,index=siglas)
print(paises)

           nome continente  extensao  corVerde
AR    Argentina    America      2780         0
BR       Brasil    America      8511         1
FR       França     Europa       644         0
IT       Italia     Europa       301         1
UK  Reino unido     Europa       244         0

In [40]:
print('----------')
num_linhas = paises.shape[0]
num_colunas = paises.shape [1]
indices= paises.index
colunas = paises.columns
paises_tipo = type(paises)
paises_dtypes = paises.dtypes
paises_idx_dtype = paises.index.dtype

----------

In [41]:
print('', num_linhas)
print('', num_colunas)
print('', indices)
print('', colunas)
print('', paises_dtypes)
print('', paises_tipo)
print('', paises_idx_dtype)

 5
 4
 Index(['AR', 'BR', 'FR', 'IT', 'UK'], dtype='object')
 Index(['nome', 'continente', 'extensao', 'corVerde'], dtype='object')
 nome          object
continente    object
extensao       int64
corVerde       int64
dtype: object
 <class 'pandas.core.frame.DataFrame'>
 object

In [42]:
print(paises.shape)

(5, 4)

In [50]:
print(paises.iloc[1][0])
print(paises.iat[1,0])
print(paises.iloc[3]['corVerde'])
print(paises.loc['IT'][1])
print(paises.loc['FR']['nome'])
print(paises.at['FR','nome'])

Brasil
Brasil
1
Europa
França
França

/tmp/ipykernel_10411/96990720.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(paises.iloc[1][0])
/tmp/ipykernel_10411/96990720.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(paises.loc['IT'][1])

In [51]:
print(paises['extensao'])

AR    2780
BR    8511
FR     644
IT     301
UK     244
Name: extensao, dtype: int64

In [52]:
paises.corVerde

AR    0
BR    1
FR    0
IT    1
UK    0
Name: corVerde, dtype: int64

In [53]:
paises.loc['BR']

nome           Brasil
continente    America
extensao         8511
corVerde            1
Name: BR, dtype: object

In [60]:
paises.loc[['BR', 'IT'], 'corVerde']

BR    1
IT    1
Name: corVerde, dtype: int64

In [63]:
paises.iloc[-2:,1:3]

   continente  extensao
IT     Europa       301
UK     Europa       244

In [68]:
tem_BR = 'BR' in paises.index
tem_US = 'US' in paises.index
print("Existe o rótulo 'BR'? ->", tem_BR)
print("Existe o rótulo 'US'? ->", tem_US)
print('-----------------------')

Existe o rótulo 'BR'? -> True
Existe o rótulo 'US'? -> False
-----------------------

In [70]:
tem_corVerde = 'corVerde' in paises.columns
tem_corAzul = 'corAzul' in paises.columns
print("existe corverde", tem_corVerde)
print("existe corazul", tem_corAzul)

existe corverde True
existe corazul False

In [71]:
tem_Brasil = paises['nome'].isin(['Brasil'])

In [72]:
print("existe o valor")
print(tem_Brasil)

existe o valor
AR    False
BR     True
FR    False
IT    False
UK    False
Name: nome, dtype: bool

In [74]:
paises.loc['JP']= {'nome': 'Japão',
                   'continente': 'Ásia',
                   'extensao': 372,
                   'corVerde': 0}

In [75]:
paises.at['BR', 'extensao']=8512

In [76]:
paises = paises.drop(['AR','UK'])

In [77]:
print('Data frame')
print(paises)

Data frame
      nome continente  extensao  corVerde
BR  Brasil    America      8512         1
FR  França     Europa       644         0
IT  Italia     Europa       301         1
JP   Japão       Ásia       372         0

In [ ]:
paises =
pd.read_csv("c:/", index_col="")